name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    name: "End-to-end ESGF STAC testing"
    if: github.repository == 'nocollier/esgf-stac-tests'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv environment
        uses: astral-sh/setup-uv@v4

      - name: Run Tests
        run: uv run pytest
